import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { FieldDataset, GridInfo } from "@containers/field_dataset.ts";
import { type AdaptiveTraceOptions, traceFieldLineAdaptive } from "@numerics/tracing.ts";
import { describe, expect, it } from "vitest";
import { SMOOTH_COMPONENTS } from "./analyticFieldCore.ts";
import { fieldArray, makeDataset } from "./fixtures.ts";
import { assertAllclose } from "./helpers.ts";

// pypic golden-trace parity: the TS tracer must reproduce pypic.traces.trace_field_line_adaptive on
// the same cell-centered f64 fields. Fixtures are generated by `npm run gen:trace-fixtures` (needs uv);
// this consumes the checked-in JSON, so no pypic at test time. reason/nPoints/nSteps/method must match
// exactly; points + maxLocalError within a measured per-fixture tolerance (the f64 drift between numpy
// np.dot and the TS loops over the trace — uniform is bit-tight since DP5(4) is exact on a constant).

const HERE = dirname(fileURLToPath(import.meta.url));

interface GoldenTrace {
  readonly points: readonly number[];
  readonly nPoints: number;
  readonly reason: string;
  readonly nSteps: number;
  readonly maxLocalError: number;
  readonly method: string;
}

interface TraceFixture {
  readonly grid: {
    readonly dimensions: [number, number, number];
    readonly spacing: [number, number, number];
    readonly origin: [number, number, number];
    readonly geometry: string;
  };
  readonly seeds: ReadonlyArray<[number, number, number]>;
  readonly options: AdaptiveTraceOptions;
  readonly inputs: { readonly B_1: number[]; readonly B_2: number[]; readonly B_3: number[] };
  readonly traces: readonly GoldenTrace[];
}

function loadFixture(name: string): TraceFixture {
  const path = join(HERE, "fixtures", "traces", `${name}.json`);
  return JSON.parse(readFileSync(path, "utf8")) as TraceFixture;
}

function datasetFrom(fix: TraceFixture): FieldDataset {
  const shape = fix.grid.dimensions;
  const grid: GridInfo = {
    dimensions: [...shape],
    spacing: [...fix.grid.spacing],
    origin: [...fix.grid.origin],
    geometry: "cartesian",
    axisLabels: ["x", "y", "z"],
    dt: null,
    boundary: null,
    survivingAxes: null,
    stagger: null,
  };
  return makeDataset(
    {
      B_1: fieldArray("B_1", Float64Array.from(fix.inputs.B_1), shape),
      B_2: fieldArray("B_2", Float64Array.from(fix.inputs.B_2), shape),
      B_3: fieldArray("B_3", Float64Array.from(fix.inputs.B_3), shape),
    },
    { grid },
  );
}

const CASES = [
  { name: "uniform", tol: { rtol: 1e-12, atol: 1e-12 } }, // DP5(4) exact on a constant field
  { name: "smooth", tol: { rtol: 1e-6, atol: 1e-9 } },
  { name: "rotational", tol: { rtol: 1e-6, atol: 1e-7 } },
] as const;

describe("field-line traces vs pypic goldens", () => {
  for (const { name, tol } of CASES) {
    it(`${name}: TS tracer reproduces pypic`, () => {
      const fix = loadFixture(name);
      const data = datasetFrom(fix);
      fix.seeds.forEach((seed, i) => {
        const golden = fix.traces[i];
        if (golden === undefined) throw new Error(`${name}: no golden for seed ${i}`);
        const fl = traceFieldLineAdaptive(data, seed, fix.options);
        expect(fl.metadata.method).toBe(golden.method);
        expect(fl.reason).toBe(golden.reason);
        expect(fl.nPoints).toBe(golden.nPoints);
        expect(fl.metadata.nSteps).toBe(golden.nSteps);
        assertAllclose(fl.points, golden.points, tol);
        expect(Math.abs(fl.metadata.maxLocalError - golden.maxLocalError)).toBeLessThanOrEqual(
          tol.atol + tol.rtol * Math.abs(golden.maxLocalError),
        );
      });
    });
  }
});

// Drift guard: the smooth fixture's inputs must equal a fresh cell-centered resample of
// SMOOTH_COMPONENTS — fails loudly if the field changes without `npm run gen:trace-fixtures`.
describe("trace fixture drift guard", () => {
  it("smooth inputs match a fresh SMOOTH_COMPONENTS resample", () => {
    const fix = loadFixture("smooth");
    const [nx, ny, nz] = fix.grid.dimensions;
    const [sx, sy, sz] = fix.grid.spacing;
    const [ox, oy, oz] = fix.grid.origin;
    const resample = (fn: (x: number, y: number, z: number) => number): Float64Array => {
      const out = new Float64Array(nx * ny * nz);
      for (let i = 0; i < nx; i++) {
        for (let j = 0; j < ny; j++) {
          for (let k = 0; k < nz; k++) {
            out[(i * ny + j) * nz + k] = fn(
              ox + (i + 0.5) * sx,
              oy + (j + 0.5) * sy,
              oz + (k + 0.5) * sz,
            );
          }
        }
      }
      return out;
    };
    assertAllclose(resample(SMOOTH_COMPONENTS[0]), fix.inputs.B_1, { rtol: 0, atol: 0 });
    assertAllclose(resample(SMOOTH_COMPONENTS[1]), fix.inputs.B_2, { rtol: 0, atol: 0 });
    assertAllclose(resample(SMOOTH_COMPONENTS[2]), fix.inputs.B_3, { rtol: 0, atol: 0 });
  });
});
