import { traceFieldLineAdaptive } from "@numerics/tracing.ts";
import { describe, expect, it } from "vitest";
import { SMOOTH_COMPONENTS } from "./analyticFieldCore.ts";
import { assertAllclose } from "./helpers.ts";
import { TOL } from "./tolerances.ts";
import { datasetFromFixture, TRACE_FIXTURES } from "./traceFixtures.ts";

// pypic golden-trace parity: the TS tracer must reproduce pypic.traces.trace_field_line_adaptive on the
// same cell-centered f64 fields. Fixtures are generated by `npm run gen:trace-fixtures` (needs uv); this
// consumes the checked-in JSON, so no pypic at test time. reason/nPoints/nSteps/method must match exactly;
// points + maxLocalError within a measured per-fixture tolerance (the f64 drift between numpy np.dot and
// the TS loops over the trace — uniform is bit-tight since DP5(4) is exact on a constant).

// smooth/rotational carry a MEASURED per-fixture bound rather than a TOL cell: the gap is numpy's
// np.dot summation order vs the TS loops, which accumulates differently per curve — not the uniform
// per-precision gap the ladder grades.
const CASES = [
  { name: "uniform", tol: TOL.trace.ts_f64 }, // DP5(4) exact on a constant field
  { name: "smooth", tol: { rtol: 1e-6, atol: 1e-9 } },
  { name: "rotational", tol: { rtol: 1e-6, atol: 1e-7 } },
] as const;

describe("field-line traces vs pypic goldens", () => {
  for (const { name, tol } of CASES) {
    it(`${name}: TS tracer reproduces pypic`, () => {
      const fix = TRACE_FIXTURES[name];
      const data = datasetFromFixture(fix);
      fix.seeds.forEach((seed, i) => {
        const golden = fix.traces[i];
        if (golden === undefined) throw new Error(`${name}: no golden for seed ${i}`);
        const fl = traceFieldLineAdaptive(data, seed, fix.options);
        expect(fl.metadata.method).toBe(golden.method);
        expect(fl.reason).toBe(golden.reason);
        expect(fl.nPoints).toBe(golden.nPoints);
        expect(fl.metadata.nSteps).toBe(golden.nSteps);
        assertAllclose(fl.points, golden.points, tol);
        expect(Math.abs(fl.metadata.maxLocalError - golden.maxLocalError)).toBeLessThanOrEqual(
          tol.atol + tol.rtol * Math.abs(golden.maxLocalError),
        );
      });
    });
  }
});

// Drift guard: the smooth fixture's inputs must equal a fresh cell-centered resample of
// SMOOTH_COMPONENTS — fails loudly if the field changes without `npm run gen:trace-fixtures`.
describe("trace fixture drift guard", () => {
  it("smooth inputs match a fresh SMOOTH_COMPONENTS resample", () => {
    const fix = TRACE_FIXTURES.smooth;
    const [nx, ny, nz] = fix.grid.dimensions;
    const [sx, sy, sz] = fix.grid.spacing;
    const [ox, oy, oz] = fix.grid.origin;
    const resample = (fn: (x: number, y: number, z: number) => number): Float64Array => {
      const out = new Float64Array(nx * ny * nz);
      for (let i = 0; i < nx; i++) {
        for (let j = 0; j < ny; j++) {
          for (let k = 0; k < nz; k++) {
            out[(i * ny + j) * nz + k] = fn(
              ox + (i + 0.5) * sx,
              oy + (j + 0.5) * sy,
              oz + (k + 0.5) * sz,
            );
          }
        }
      }
      return out;
    };
    // The f64 reference floor, not bit-exactness: the fixture was generated on one platform and
    // this resample runs on another, and libm transcendentals differ by ~1 ULP between them. Any
    // real drift (an edited component or sampling convention) moves values far above 1e-12.
    assertAllclose(resample(SMOOTH_COMPONENTS[0]), fix.inputs.B_1);
    assertAllclose(resample(SMOOTH_COMPONENTS[1]), fix.inputs.B_2);
    assertAllclose(resample(SMOOTH_COMPONENTS[2]), fix.inputs.B_3);
  });
});
