import { readFileSync } from "node:fs";

export interface RecipeMetaJson {
  readonly func: string;
  readonly fields: readonly string[];
  readonly speciesIndex: number | null;
  readonly needsGrid: boolean;
  readonly needsGamma: boolean;
  readonly needsC: boolean;
  readonly component: number | null;
  readonly speciesArgs: string | null;
  readonly passesGeometry: boolean;
  readonly supportsRelativistic: boolean;
}

export interface SpeciesTemplateJson {
  readonly func: string;
  readonly fieldPattern: readonly string[];
  readonly speciesArgs: string;
  readonly needsGamma: boolean;
  readonly needsC: boolean;
  readonly component: number | null;
}

export interface FieldInfoJson {
  readonly quantityType: string;
  readonly longName: string;
  readonly siUnit: string;
  readonly latex: string;
  readonly unitDimension: readonly number[] | null;
}

export interface Bundle {
  readonly schemaVersion: string;
  readonly jsonSchema: unknown;
  readonly computeAliases: Record<string, string>;
  readonly groupAliases: Record<string, string>;
  readonly speciesSuffixRe: string;
  readonly recipes: Record<string, RecipeMetaJson>;
  readonly speciesTemplates: Record<string, SpeciesTemplateJson>;
  readonly fields: Record<string, FieldInfoJson>;
}

export function loadBundle(path: string): Bundle {
  // Shape is the contract emitted by `pypic export bundle`; validated downstream
  // by the renderers (and ultimately by tsc on their output).
  return JSON.parse(readFileSync(path, "utf8")) as Bundle;
}

export const BANNER =
  "// @generated by scripts/codegen — do not edit.\n" +
  "// Source: `npm run gen:export` (pypic export bundle).\n\n";
