// @generated by scripts/codegen — do not edit.
// Source: `npm run gen:export` (pypic export bundle).

import { z } from "zod";

export const SimulationSchema = z
  .object({
    bodies: z
      .array(
        z
          .object({
            center: z.any(),
            dipole_center_offset: z.union([z.any(), z.null()]).default(null),
            has_atmosphere: z.union([z.boolean(), z.null()]).default(null),
            has_intrinsic_field: z.union([z.boolean(), z.null()]).default(null),
            intrinsic_dipole: z.union([z.any(), z.null()]).default(null),
            mass: z.union([z.number().gt(0), z.null()]).default(null),
            name: z.string(),
            radius: z.union([z.number().gt(0), z.null()]).default(null),
            rotation_axis: z.union([z.any(), z.null()]).default(null),
            rotation_period: z.union([z.number().gte(0), z.null()]).default(null),
            shape: z.enum(["sphere", "torus", "cuboid", "mesh"]).default("sphere"),
            surface_absorbs_ions: z.union([z.boolean(), z.null()]).default(null),
          })
          .strict()
          .describe("One entry in ``[[bodies]]`` — registry of physical objects."),
      )
      .optional(),
    boundary_conditions: z
      .union([
        z
          .object({
            drivers_lower: z
              .union([
                z.record(z.string(), z.union([z.any(), z.string()])).superRefine((value, ctx) => {
                  for (const key in value) {
                    let evaluated = false;
                    if (key.match(new RegExp("^x[-_]"))) {
                      evaluated = true;
                      const result = z.any().safeParse(value[key]);
                      if (!result.success) {
                        ctx.addIssue({
                          path: [key],
                          code: "custom",
                          message: `Invalid input: Key matching regex /${key}/ must match schema`,
                          params: {
                            issues: result.error.issues,
                          },
                        });
                      }
                    }
                    if (!evaluated) {
                      const result = z.string().safeParse(value[key]);
                      if (!result.success) {
                        ctx.addIssue({
                          path: [key],
                          code: "custom",
                          message: `Invalid input: must match catchall schema`,
                          params: {
                            issues: result.error.issues,
                          },
                        });
                      }
                    }
                  }
                }),
                z.null(),
              ])
              .default(null),
            drivers_upper: z
              .union([
                z.record(z.string(), z.union([z.any(), z.string()])).superRefine((value, ctx) => {
                  for (const key in value) {
                    let evaluated = false;
                    if (key.match(new RegExp("^x[-_]"))) {
                      evaluated = true;
                      const result = z.any().safeParse(value[key]);
                      if (!result.success) {
                        ctx.addIssue({
                          path: [key],
                          code: "custom",
                          message: `Invalid input: Key matching regex /${key}/ must match schema`,
                          params: {
                            issues: result.error.issues,
                          },
                        });
                      }
                    }
                    if (!evaluated) {
                      const result = z.string().safeParse(value[key]);
                      if (!result.success) {
                        ctx.addIssue({
                          path: [key],
                          code: "custom",
                          message: `Invalid input: must match catchall schema`,
                          params: {
                            issues: result.error.issues,
                          },
                        });
                      }
                    }
                  }
                }),
                z.null(),
              ])
              .default(null),
            field_overrides: z
              .union([
                z
                  .record(
                    z.string(),
                    z.union([
                      z.any(),
                      z
                        .object({
                          drivers_lower: z
                            .union([
                              z
                                .record(z.string(), z.union([z.any(), z.string()]))
                                .superRefine((value, ctx) => {
                                  for (const key in value) {
                                    let evaluated = false;
                                    if (key.match(new RegExp("^x[-_]"))) {
                                      evaluated = true;
                                      const result = z.any().safeParse(value[key]);
                                      if (!result.success) {
                                        ctx.addIssue({
                                          path: [key],
                                          code: "custom",
                                          message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                          params: {
                                            issues: result.error.issues,
                                          },
                                        });
                                      }
                                    }
                                    if (!evaluated) {
                                      const result = z.string().safeParse(value[key]);
                                      if (!result.success) {
                                        ctx.addIssue({
                                          path: [key],
                                          code: "custom",
                                          message: `Invalid input: must match catchall schema`,
                                          params: {
                                            issues: result.error.issues,
                                          },
                                        });
                                      }
                                    }
                                  }
                                }),
                              z.null(),
                            ])
                            .default(null),
                          drivers_upper: z
                            .union([
                              z
                                .record(z.string(), z.union([z.any(), z.string()]))
                                .superRefine((value, ctx) => {
                                  for (const key in value) {
                                    let evaluated = false;
                                    if (key.match(new RegExp("^x[-_]"))) {
                                      evaluated = true;
                                      const result = z.any().safeParse(value[key]);
                                      if (!result.success) {
                                        ctx.addIssue({
                                          path: [key],
                                          code: "custom",
                                          message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                          params: {
                                            issues: result.error.issues,
                                          },
                                        });
                                      }
                                    }
                                    if (!evaluated) {
                                      const result = z.string().safeParse(value[key]);
                                      if (!result.success) {
                                        ctx.addIssue({
                                          path: [key],
                                          code: "custom",
                                          message: `Invalid input: must match catchall schema`,
                                          params: {
                                            issues: result.error.issues,
                                          },
                                        });
                                      }
                                    }
                                  }
                                }),
                              z.null(),
                            ])
                            .default(null),
                          lower: z.array(z.string()).min(1).max(3),
                          upper: z.array(z.string()).min(1).max(3),
                        })
                        .strict()
                        .describe(
                          'Reusable per-face BC vector + optional driver foreign keys.\n\n``lower`` / ``upper`` carry one tag per axis (``"periodic"``,\n``"reflecting"``, ``"open"``, ``"driven"``, ...). The vocabulary is\nfree-form: validators don\'t constrain the strings, so different code\nfamilies coexist without an upstream enum cut.\n\n``drivers_lower`` / ``drivers_upper`` link individual faces to a\ndeclared ``[[drivers]].name`` entry. Each is sparse: a dict keyed by\naxis index as a string (``"0"``, ``"1"``, ``"2"``), valued with the\ndriver name. Faces without a driver simply don\'t appear. The root\nvalidator enforces foreign-key resolution against ``[[drivers]]``\nand the axis-index range against ``grid.dimensions``.',
                        ),
                    ]),
                  )
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = false;
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z
                          .object({
                            drivers_lower: z
                              .union([
                                z
                                  .record(z.string(), z.union([z.any(), z.string()]))
                                  .superRefine((value, ctx) => {
                                    for (const key in value) {
                                      let evaluated = false;
                                      if (key.match(new RegExp("^x[-_]"))) {
                                        evaluated = true;
                                        const result = z.any().safeParse(value[key]);
                                        if (!result.success) {
                                          ctx.addIssue({
                                            path: [key],
                                            code: "custom",
                                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                            params: {
                                              issues: result.error.issues,
                                            },
                                          });
                                        }
                                      }
                                      if (!evaluated) {
                                        const result = z.string().safeParse(value[key]);
                                        if (!result.success) {
                                          ctx.addIssue({
                                            path: [key],
                                            code: "custom",
                                            message: `Invalid input: must match catchall schema`,
                                            params: {
                                              issues: result.error.issues,
                                            },
                                          });
                                        }
                                      }
                                    }
                                  }),
                                z.null(),
                              ])
                              .default(null),
                            drivers_upper: z
                              .union([
                                z
                                  .record(z.string(), z.union([z.any(), z.string()]))
                                  .superRefine((value, ctx) => {
                                    for (const key in value) {
                                      let evaluated = false;
                                      if (key.match(new RegExp("^x[-_]"))) {
                                        evaluated = true;
                                        const result = z.any().safeParse(value[key]);
                                        if (!result.success) {
                                          ctx.addIssue({
                                            path: [key],
                                            code: "custom",
                                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                            params: {
                                              issues: result.error.issues,
                                            },
                                          });
                                        }
                                      }
                                      if (!evaluated) {
                                        const result = z.string().safeParse(value[key]);
                                        if (!result.success) {
                                          ctx.addIssue({
                                            path: [key],
                                            code: "custom",
                                            message: `Invalid input: must match catchall schema`,
                                            params: {
                                              issues: result.error.issues,
                                            },
                                          });
                                        }
                                      }
                                    }
                                  }),
                                z.null(),
                              ])
                              .default(null),
                            lower: z.array(z.string()).min(1).max(3),
                            upper: z.array(z.string()).min(1).max(3),
                          })
                          .strict()
                          .describe(
                            'Reusable per-face BC vector + optional driver foreign keys.\n\n``lower`` / ``upper`` carry one tag per axis (``"periodic"``,\n``"reflecting"``, ``"open"``, ``"driven"``, ...). The vocabulary is\nfree-form: validators don\'t constrain the strings, so different code\nfamilies coexist without an upstream enum cut.\n\n``drivers_lower`` / ``drivers_upper`` link individual faces to a\ndeclared ``[[drivers]].name`` entry. Each is sparse: a dict keyed by\naxis index as a string (``"0"``, ``"1"``, ``"2"``), valued with the\ndriver name. Faces without a driver simply don\'t appear. The root\nvalidator enforces foreign-key resolution against ``[[drivers]]``\nand the axis-index range against ``grid.dimensions``.',
                          )
                          .safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  }),
                z.null(),
              ])
              .default(null),
            lower: z.array(z.string()).min(1).max(3),
            upper: z.array(z.string()).min(1).max(3),
          })
          .strict()
          .describe(
            "``[boundary_conditions]`` — per-face tag arrays.\n\nThe default form: one tag per face per axis applied uniformly to\nevery field. ``field_overrides`` lets PIC PML simulations and\nsolar-wind-driven runs declare *different* BCs for E (PML), B (PML),\nand particles (reflecting / absorbing / thermal-bath) at the same\nface. Each entry is a :class:`BoundaryConditionsBase` matching the\nsame axis count as the default.",
          ),
        z.null(),
      ])
      .default(null),
    collisions: z
      .array(
        z
          .object({
            coulomb_log: z.union([z.number().gt(0), z.null()]).default(null),
            description: z.union([z.string(), z.null()]).default(null),
            model: z.string(),
            species_pair: z.array(z.string()).min(2).max(2),
            temperature_ref: z.union([z.number().gt(0), z.null()]).default(null),
          })
          .catchall(z.union([z.any(), z.any()]))
          .superRefine((value, ctx) => {
            for (const key in value) {
              let evaluated = [
                "coulomb_log",
                "description",
                "model",
                "species_pair",
                "temperature_ref",
              ].includes(key);
              if (key.match(new RegExp("^x[-_]"))) {
                evaluated = true;
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
              if (!evaluated) {
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: must match catchall schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
            }
          })
          .describe(
            "One entry in ``[[collisions]]`` — inter-species collision model.\n\nCollisional PIC codes (Smilei, EPOCH, OSIRIS-collisional, PIConGPU)\ndeclare per-pair Coulomb collisions, BGK relaxation, or\nMonte-Carlo scattering. The schema captures the *declaration* of\neach pair; numerical parameters live on the entry.\n\n``species_pair`` lists the two species names participating; the\nroot validator enforces that both names exist in ``[[species]]``.\nSelf-collisions (same species twice) are permitted.\n\nExtra keys are accepted (``_ExtensibleBase``) so code-specific\nknobs — cross-section table paths, BGK relaxation-rate models,\nMonte-Carlo scattering-table identifiers — can land here without\nforcing every collisional reader through the top-level ``x-``\nnamespace. Portable additions (when a vocabulary stabilises across\ncodes) become typed fields in a future version.",
          ),
      )
      .optional(),
    coordinates: z
      .object({
        axis_labels: z.union([z.any(), z.null()]).default(null),
        frame: z.string(),
        geometry: z.enum(["cartesian", "spherical", "cylindrical", "thetaMode"]),
        modes: z
          .union([
            z
              .object({
                mode_indices: z.union([z.array(z.number().int().gte(0)), z.null()]).default(null),
                n_modes: z.number().int().gt(0),
              })
              .strict()
              .describe(
                '``[coordinates.modes]`` — azimuthal-mode decomposition for FBPIC RZ.\n\nRequired when ``geometry = "thetaMode"``. ``n_modes`` counts the\nazimuthal modes stored on disk (typically 1–3, with mode 0 cylindrically\nsymmetric). ``mode_indices`` is an optional explicit list of mode\nnumbers — when omitted, modes are assumed to run ``0, 1, ..., n_modes-1``.',
              ),
            z.null(),
          ])
          .default(null),
        physical_extent: z.union([z.any(), z.null()]).default(null),
        physical_extent_unit: z
          .union([z.enum(["m", "km", "R_E", "R_S", "R_sun", "R_M", "R_J", "AU", "d_i"]), z.null()])
          .default(null),
        transforms: z
          .record(
            z.string(),
            z.union([
              z.any(),
              z
                .object({
                  axis_labels: z.union([z.any(), z.null()]).default(null),
                  from_frame: z.union([z.string(), z.null()]).default(null),
                  origin: z.union([z.any(), z.null()]).default(null),
                  parameter: z.union([z.string(), z.null()]).default(null),
                  rotation: z.union([z.array(z.any()), z.null()]).default(null),
                  scale: z.union([z.number(), z.null()]).default(null),
                })
                .strict()
                .describe(
                  "One entry under ``[coordinates.transforms.<frame>]``.\n\n``rotation``, when present, must be a 3×3 *signed permutation*\nmatrix: exactly one ±1 per row and per column with every other\nentry zero. That covers all axis-relabeling / handedness flips\npypic's frame transforms support today (GSE↔GSM-style rotations\nwith continuous angles are time-dependent and route through\n``parameter`` instead — see ``coordinates.transforms``). Catching\na malformed matrix here is cheaper than letting it slip into\n``pypic.coordinates._frames`` and surface as a runtime error at\napply time.",
                ),
            ]),
          )
          .superRefine((value, ctx) => {
            for (const key in value) {
              let evaluated = false;
              if (key.match(new RegExp("^x[-_]"))) {
                evaluated = true;
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
              if (!evaluated) {
                const result = z
                  .object({
                    axis_labels: z.union([z.any(), z.null()]).default(null),
                    from_frame: z.union([z.string(), z.null()]).default(null),
                    origin: z.union([z.any(), z.null()]).default(null),
                    parameter: z.union([z.string(), z.null()]).default(null),
                    rotation: z.union([z.array(z.any()), z.null()]).default(null),
                    scale: z.union([z.number(), z.null()]).default(null),
                  })
                  .strict()
                  .describe(
                    "One entry under ``[coordinates.transforms.<frame>]``.\n\n``rotation``, when present, must be a 3×3 *signed permutation*\nmatrix: exactly one ±1 per row and per column with every other\nentry zero. That covers all axis-relabeling / handedness flips\npypic's frame transforms support today (GSE↔GSM-style rotations\nwith continuous angles are time-dependent and route through\n``parameter`` instead — see ``coordinates.transforms``). Catching\na malformed matrix here is cheaper than letting it slip into\n``pypic.coordinates._frames`` and surface as a runtime error at\napply time.",
                  )
                  .safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: must match catchall schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
            }
          })
          .optional(),
      })
      .strict()
      .describe(
        '``[coordinates]`` — geometry + reference frame.\n\n``physical_extent`` is metadata at the schema level: the validator\nonly checks shape and positivity. Post-translation, the reader-side\nhelper ``pypic.readers.config.apply_physical_extent`` consumes it to\nauto-compute transform scale factors and a shrink-factor diagnostic\n(see ``docs/schema.md`` § Coordinates).\n\n``modes`` is required when ``geometry = "thetaMode"`` (FBPIC azimuthal-\nmode decomposition over an (r, z) grid) and forbidden otherwise.',
      ),
    drivers: z
      .array(
        z
          .object({
            body: z.union([z.string(), z.null()]).default(null),
            cadence: z.union([z.number().gte(0), z.null()]).default(null),
            columns: z.union([z.array(z.string()), z.null()]).default(null),
            coupling: z.enum(["boundary", "volume", "source", "sink"]),
            description: z.union([z.string(), z.null()]).default(null),
            direction: z.enum(["one_way", "two_way"]).default("one_way"),
            interpolation: z.union([z.string(), z.null()]).default(null),
            model: z
              .union([
                z
                  .object({
                    description: z.union([z.string(), z.null()]).default(null),
                    name: z.string(),
                    type: z.string(),
                    url: z.union([z.string(), z.null()]).default(null),
                  })
                  .catchall(z.union([z.any(), z.any()]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = ["description", "name", "type", "url"].includes(key);
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  })
                  .describe(
                    '``[drivers.model]`` — identity of a coupled external system.\n\nUsed when a driver entry refers to a *named model* rather than (or\nin addition to) a flat data file. The type vocabulary is open:\n``"MHD"`` and ``"PIC"`` cover pypic-aware peers, but\n``"ionosphere_potential_solver"`` (RIM, Weimer), ``"magnetic_field_\nextrapolation"`` (PFSS, NLFFF), ``"fluid_atmosphere"`` (GITM, TIE-\nGCM), ``"fusion_transport"`` (ASTRA, JETTO), and any other category\nare equally valid.\n\n``url`` is a single opaque pointer. It may be the peer\'s\n``simulation.toml`` cross-link (when pypic-aware), a homepage URL,\na DOI, or any other machine- or human-readable metadata reference.\nThe schema does not resolve or sniff the format — that is a consumer\nconcern, in the same spirit as ``restart.from`` and the top-level\n``[model].url``. A non-standard metadata file is better than no\nlink at all.\n\n``_ExtensibleBase`` lets coupling-specific keys (``version``,\n``doi``, ``git_sha``, model-specific knobs) ride along without\nbloating the typed surface.',
                  ),
                z.null(),
              ])
              .default(null),
            name: z.string(),
            source: z.union([z.string(), z.null()]).default(null),
            target_lower: z.union([z.any(), z.null()]).default(null),
            target_upper: z.union([z.any(), z.null()]).default(null),
            type: z.string(),
          })
          .catchall(z.union([z.any(), z.any()]))
          .superRefine((value, ctx) => {
            for (const key in value) {
              let evaluated = [
                "body",
                "cadence",
                "columns",
                "coupling",
                "description",
                "direction",
                "interpolation",
                "model",
                "name",
                "source",
                "target_lower",
                "target_upper",
                "type",
              ].includes(key);
              if (key.match(new RegExp("^x[-_]"))) {
                evaluated = true;
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
              if (!evaluated) {
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: must match catchall schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
            }
          })
          .describe(
            "One entry in ``[[drivers]]``.\n\nDrivers have a core set of v1.0 fields plus driver-type-specific\nkeys — extra keys allowed so individual driver types (magnetogram,\nsolar_wind_timeseries, pickup_ion_source, ...) don't need a model\nper type in v1.0.\n\nAn entry describes the *external input from this run's\nperspective*. For two-way coupling (``direction = \"two_way\"``),\nthe asymmetry is in information flow, not in physics: the peer\nrun, if pypic-aware, owns its own ``simulation.toml`` with its\nown ``[[drivers]]`` entry pointing back. ``[drivers.model]`` is\nwhere the peer's identity (name, type, url, description) lives;\npure data drivers (CSV, HDF5 timeseries) can omit the sub-table\nand use ``source`` alone.",
          ),
      )
      .optional(),
    grid: z
      .object({
        amr: z
          .union([
            z
              .object({
                amr_kind: z.enum(["block", "patch", "octree"]).default("block"),
                block_size: z.union([z.array(z.number().int().gt(0)), z.null()]).default(null),
                level_subcycling: z.boolean().default(false),
                max_level: z.number().int().gte(0),
                refinement_criteria: z.array(z.string()).optional(),
                refinement_ratio: z.number().int().gt(0).default(2),
                refinement_threshold: z.union([z.number().gte(0), z.null()]).default(null),
              })
              .strict()
              .describe(
                "``[grid.amr]`` — dynamic adaptive refinement parameters.\n\n``amr_kind`` discriminates block/patch (BoxLib / AMReX / Chombo / FLASH)\nfrom octree codes (RAMSES, MPI-AMRVAC); octree leaves are single cells\nso ``block_size`` does not apply. ``level_subcycling`` records whether\ndifferent AMR levels advance at different effective timesteps (Athena++\nand AMReX-based codes); a per-level ``dt_factor`` array would be a\nfuture v1.1 add if needed.",
              ),
            z.null(),
          ])
          .default(null),
        dimensions: z.array(z.number().int().gt(0)).min(1).max(3),
        ghost_cells: z
          .union([z.array(z.number().int().gte(0)).min(1).max(3), z.null()])
          .default(null),
        lower: z.any(),
        refinement: z
          .array(
            z
              .object({
                box: z.array(z.array(z.number())).min(2).max(2),
                level: z.number().int().gte(0),
              })
              .strict()
              .describe("One entry in ``[[grid.refinement]]`` (static nested refinement box)."),
          )
          .optional(),
        source: z.union([z.string(), z.null()]).default(null),
        source_format: z.union([z.string(), z.null()]).default(null),
        spacing: z.any(),
        stagger: z
          .object({
            convention: z.enum(["cell", "node", "staggered"]).default("cell"),
            fields: z
              .union([
                z
                  .record(z.string(), z.union([z.any(), z.enum(["cell", "node", "face", "edge"])]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = false;
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z
                          .enum(["cell", "node", "face", "edge"])
                          .safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  }),
                z.null(),
              ])
              .default(null),
            position: z
              .union([
                z
                  .record(z.string(), z.union([z.any(), z.array(z.number())]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = false;
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z.array(z.number()).safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  }),
                z.null(),
              ])
              .default(null),
          })
          .strict()
          .describe(
            '``[grid.stagger]`` — where fields live inside each cell.\n\nThree tiers, all optional and additive — same fact at increasing\nprecision:\n\n1. ``convention`` — single-string summary (``"cell"`` / ``"node"``\n   / ``"staggered"``). Defaults to ``"cell"``.\n2. ``fields`` — per-field-group location map, e.g.\n   ``{B = "face", E = "edge"}``. Captures the Yee-mesh truth that\n   a single string cannot.\n3. ``position`` — per-component openPMD ED-PIC offsets in\n   ``[0, 1)`` along each axis, e.g. ``{B_1 = [0.5, 0.0, 0.0]}``.\n   Lossless representation of the source mesh; consumed by readers\n   that need ED-PIC-precise destaggering.\n\nAll three are informational — readers destagger to co-located grids\non load. They round-trip through :class:`StaggerInfo` in\n``pypic.containers``. The validator does not cross-check between\ntiers; a writer may populate any subset.',
          )
          .optional(),
        stretched: z
          .union([
            z
              .object({
                axis_widths: z
                  .record(z.string(), z.union([z.any(), z.array(z.number().gt(0))]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = false;
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z.array(z.number().gt(0)).safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  }),
                sum_rtol: z.number().gte(0).default(1e-9),
              })
              .strict()
              .describe(
                '``[grid.stretched]`` — non-uniform per-axis cell widths.\n\nSparse, keyed by axis index as a string (``"0"`` / ``"1"`` / ``"2"``).\nOnly stretched axes appear; uniform axes inherit ``Grid.spacing``.\nPer-axis cell widths must sum to ``upper[i] - lower[i]`` and the\nlist length must equal ``dimensions[i]``; both invariants are\nenforced by ``Grid._check_axis_consistency``.\n\nAdopted to describe ARMS spherical-r stretches, PLUTO log-radial\ngrids, Athena++ stretched grids, and FLASH per-block-non-uniform\nlayouts losslessly. Kept additive so uniform documents validate\nunchanged. Metric-aware operators are out of scope for v1.0.x —\nconsumers that need them should guard explicitly.',
              ),
            z.null(),
          ])
          .default(null),
        upper: z.any(),
      })
      .strict()
      .describe(
        "``[grid]`` — computational grid in code units.\n\n``ghost_cells`` records the number of ghost cells per axis used by the\ncode's halo exchange. Optional metadata for downstream edge-derivative\nanalysis; readers strip ghosts before populating ``FieldDataset``.\n\n``stretched`` describes per-axis non-uniform cell widths. Sparse —\nonly axes with non-uniform spacing appear in\n``[grid.stretched.axis_widths]``; the remaining axes inherit\n``spacing``. The validator enforces that any listed axis widths sum\nto ``upper[i] - lower[i]`` and that the list length equals\n``dimensions[i]``.\n\n``stagger`` consolidates the three field-placement-inside-cell\ntiers (``convention``, ``fields``, ``position``) under a single\nsub-table — see :class:`GridStagger`.",
      ),
    initial_conditions: z
      .union([
        z
          .object({ type: z.string() })
          .catchall(z.union([z.any(), z.any()]))
          .superRefine((value, ctx) => {
            for (const key in value) {
              let evaluated = ["type"].includes(key);
              if (key.match(new RegExp("^x[-_]"))) {
                evaluated = true;
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
              if (!evaluated) {
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: must match catchall schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
            }
          })
          .describe("``[initial_conditions]`` — flat table, setup-specific keys vary."),
        z.null(),
      ])
      .default(null),
    model: z
      .object({
        authors: z.array(z.any()).optional(),
        description: z.union([z.string(), z.null()]).default(null),
        doi: z.union([z.string(), z.null()]).default(null),
        license: z.union([z.string(), z.null()]).default(null),
        name: z.string(),
        type: z.enum(["PIC", "MHD", "hybrid", "vlasov", "gyrokinetic"]),
        url: z.union([z.string(), z.null()]).default(null),
        version: z.union([z.string(), z.null()]).default(null),
      })
      .strict()
      .describe("``[model]`` — identity of the code that produced the data."),
    output: z
      .union([
        z
          .object({
            checkpoints: z
              .union([
                z
                  .object({
                    dir: z.string(),
                    file_pattern: z.union([z.string(), z.null()]).default(null),
                    files_per_step: z.union([z.number().int().gt(0), z.null()]).default(null),
                    format: z.enum(["hdf5", "zarr", "adios2", "netcdf"]).default("hdf5"),
                    keep_last: z.union([z.number().int().gt(0), z.null()]).default(null),
                    partition: z
                      .union([z.enum(["by_rank", "by_field", "monolithic"]), z.null()])
                      .default(null),
                    precision: z.enum(["f32", "f64"]).default("f64"),
                    step_interval: z.number().int().gt(0),
                  })
                  .strict()
                  .describe("``[output.checkpoints]`` — lossless full-state dumps."),
                z.null(),
              ])
              .default(null),
            diagnostics: z
              .union([
                z
                  .object({
                    dir: z.string(),
                    file_pattern: z.union([z.string(), z.null()]).default(null),
                    files_per_step: z.union([z.number().int().gt(0), z.null()]).default(null),
                    format: z.enum(["hdf5", "zarr", "adios2", "netcdf"]).default("hdf5"),
                    partition: z
                      .union([z.enum(["by_rank", "by_field", "monolithic"]), z.null()])
                      .default(null),
                    precision: z.enum(["f32", "f64"]).default("f32"),
                    quantities: z.array(z.string()),
                    step_interval: z.number().int().gt(0),
                  })
                  .strict()
                  .describe("``[output.diagnostics]`` — on-the-fly derived quantities."),
                z.null(),
              ])
              .default(null),
            fields: z
              .union([
                z
                  .object({
                    dir: z.string(),
                    file_pattern: z.union([z.string(), z.null()]).default(null),
                    files_per_step: z.union([z.number().int().gt(0), z.null()]).default(null),
                    format: z.enum(["hdf5", "zarr", "adios2", "netcdf"]).default("hdf5"),
                    partition: z
                      .union([z.enum(["by_rank", "by_field", "monolithic"]), z.null()])
                      .default(null),
                    precision: z.enum(["f32", "f64"]).default("f32"),
                    precision_overrides: z
                      .record(z.string(), z.union([z.any(), z.enum(["f32", "f64"])]))
                      .superRefine((value, ctx) => {
                        for (const key in value) {
                          let evaluated = false;
                          if (key.match(new RegExp("^x[-_]"))) {
                            evaluated = true;
                            const result = z.any().safeParse(value[key]);
                            if (!result.success) {
                              ctx.addIssue({
                                path: [key],
                                code: "custom",
                                message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                params: {
                                  issues: result.error.issues,
                                },
                              });
                            }
                          }
                          if (!evaluated) {
                            const result = z.enum(["f32", "f64"]).safeParse(value[key]);
                            if (!result.success) {
                              ctx.addIssue({
                                path: [key],
                                code: "custom",
                                message: `Invalid input: must match catchall schema`,
                                params: {
                                  issues: result.error.issues,
                                },
                              });
                            }
                          }
                        }
                      })
                      .optional(),
                    quantities: z.array(z.string()),
                    step_interval: z.number().int().gt(0),
                  })
                  .strict()
                  .describe("``[output.fields]`` — field output cadence + quantities."),
                z.null(),
              ])
              .default(null),
            particles: z
              .union([
                z
                  .object({
                    dir: z.string(),
                    file_pattern: z.union([z.string(), z.null()]).default(null),
                    files_per_step: z.union([z.number().int().gt(0), z.null()]).default(null),
                    format: z.enum(["hdf5", "zarr", "adios2", "netcdf"]).default("hdf5"),
                    include_energy: z.boolean().default(false),
                    include_ids: z.boolean().default(false),
                    partition: z
                      .union([z.enum(["by_rank", "by_field", "monolithic"]), z.null()])
                      .default(null),
                    precision: z.enum(["f32", "f64"]).default("f32"),
                    sample: z.union([z.number(), z.number().int(), z.null()]).default(null),
                    species: z.array(z.string()),
                    step_interval: z.number().int().gt(0),
                  })
                  .strict()
                  .describe("``[output.particles]`` — particle output cadence + selection."),
                z.null(),
              ])
              .default(null),
            probes: z
              .union([
                z
                  .object({
                    dir: z.string(),
                    file_pattern: z.union([z.string(), z.null()]).default(null),
                    files_per_step: z.union([z.number().int().gt(0), z.null()]).default(null),
                    format: z.enum(["hdf5", "zarr", "adios2", "netcdf"]).default("hdf5"),
                    partition: z
                      .union([z.enum(["by_rank", "by_field", "monolithic"]), z.null()])
                      .default(null),
                    precision: z.enum(["f32", "f64"]).default("f64"),
                    step_interval: z.number().int().gt(0),
                  })
                  .strict()
                  .describe("``[output.probes]`` — probe time-series cadence."),
                z.null(),
              ])
              .default(null),
            streams: z
              .array(
                z
                  .object({
                    dir: z.string(),
                    file_pattern: z.union([z.string(), z.null()]).default(null),
                    files_per_step: z.union([z.number().int().gt(0), z.null()]).default(null),
                    format: z.enum(["hdf5", "zarr", "adios2", "netcdf"]).default("hdf5"),
                    name: z.string(),
                    partition: z
                      .union([z.enum(["by_rank", "by_field", "monolithic"]), z.null()])
                      .default(null),
                    precision: z.enum(["f32", "f64"]).default("f32"),
                    precision_overrides: z
                      .record(z.string(), z.union([z.any(), z.enum(["f32", "f64"])]))
                      .superRefine((value, ctx) => {
                        for (const key in value) {
                          let evaluated = false;
                          if (key.match(new RegExp("^x[-_]"))) {
                            evaluated = true;
                            const result = z.any().safeParse(value[key]);
                            if (!result.success) {
                              ctx.addIssue({
                                path: [key],
                                code: "custom",
                                message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                params: {
                                  issues: result.error.issues,
                                },
                              });
                            }
                          }
                          if (!evaluated) {
                            const result = z.enum(["f32", "f64"]).safeParse(value[key]);
                            if (!result.success) {
                              ctx.addIssue({
                                path: [key],
                                code: "custom",
                                message: `Invalid input: must match catchall schema`,
                                params: {
                                  issues: result.error.issues,
                                },
                              });
                            }
                          }
                        }
                      })
                      .optional(),
                    quantities: z.array(z.string()),
                    region: z
                      .union([
                        z.any().superRefine((x, ctx) => {
                          const schemas = [
                            z
                              .object({
                                kind: z.literal("box").default("box"),
                                lower: z.any(),
                                upper: z.any(),
                              })
                              .strict()
                              .describe(
                                "``[output.streams.<n>.region]`` — axis-aligned box selection.\n\nCoordinates in code units (matches ``[grid].lower`` / ``[grid].upper``\nconvention). ``upper`` must be strictly greater than ``lower`` per\naxis; the per-axis count must align with ``[grid].dimensions`` —\nenforced at the root level.",
                              ),
                            z
                              .object({
                                axis: z.number().int().gte(0).lte(2),
                                kind: z.literal("plane").default("plane"),
                                value: z.number(),
                              })
                              .strict()
                              .describe(
                                "``[output.streams.<n>.region]`` — single-axis plane slice.\n\n``axis`` selects a coordinate axis (``0``/``1``/``2``).\n``value`` is the plane position in code units; the reader is\nresponsible for resolving it to the nearest grid index.",
                              ),
                          ];
                          const { errors, failed } = schemas.reduce<{
                            errors: z.core.$ZodIssue[];
                            failed: number;
                          }>(
                            ({ errors, failed }, schema) =>
                              ((result) =>
                                result.error
                                  ? {
                                      errors: [...errors, ...result.error.issues],
                                      failed: failed + 1,
                                    }
                                  : { errors, failed })(schema.safeParse(x)),
                            { errors: [], failed: 0 },
                          );
                          const passed = schemas.length - failed;
                          if (passed !== 1) {
                            ctx.addIssue(
                              errors.length
                                ? {
                                    path: [],
                                    code: "invalid_union",
                                    errors: [errors],
                                    message:
                                      "Invalid input: Should pass single schema. Passed " + passed,
                                  }
                                : {
                                    path: [],
                                    code: "custom",
                                    errors: [errors],
                                    message:
                                      "Invalid input: Should pass single schema. Passed " + passed,
                                  },
                            );
                          }
                        }),
                        z.null(),
                      ])
                      .default(null),
                    step_interval: z.number().int().gt(0),
                  })
                  .strict()
                  .describe(
                    "One entry in ``[[output.streams]]`` — multi-cadence / ROI output.\n\nThe repeatable form alongside the existing singleton ``[output.fields]``.\nUse this for runs that write moments at 10x the cadence of full\ndistributions, or ROI slabs at 10x the cadence of the global volume,\nor that simply need named output groups for downstream pipelines.\n\n``name`` is required and must be unique across streams. ``region``\noptionally restricts the write to a sub-volume or plane;\n``precision_overrides`` re-uses the ``[output.fields]`` semantics\n(per-field-name dtype overrides; names must appear in ``quantities``).",
                  ),
              )
              .optional(),
          })
          .strict()
          .describe("``[output]`` — umbrella for all write-side configuration."),
        z.null(),
      ])
      .default(null),
    phase_space: z
      .union([
        z
          .object({
            axis_labels: z.union([z.array(z.string()), z.null()]).default(null),
            coordinate_system: z
              .enum(["cartesian", "guiding-center", "field-aligned", "spherical-velocity"])
              .default("cartesian"),
            dimensions: z.array(z.number().int().gt(0)).min(2).max(6),
            extents: z.union([z.array(z.array(z.number())), z.null()]).default(null),
            storage: z
              .union([
                z
                  .object({
                    block_size: z.union([z.array(z.number().int().gt(0)), z.null()]).default(null),
                    sparsity_threshold: z.union([z.number().gte(0), z.null()]).default(null),
                  })
                  .strict()
                  .describe(
                    "``[phase_space.storage]`` — sparse-block velocity-grid storage.\n\nContinuum-Vlasov codes (Vlasiator, Gkeyll-Vlasov-Maxwell) subdivide\nthe velocity sub-grid into blocks for adaptive memory use, dropping\nblocks whose distribution-function density falls below a threshold.\n``block_size`` records the per-velocity-axis block factor;\n``sparsity_threshold`` records the density floor.\n\nOptional sub-table on :class:`PhaseSpace`. Gyrokinetic codes\n(GENE, GS2, GX, Gkeyll-GK) emit dense 5-D grids and omit this\nblock entirely. The validator checks that ``block_size`` length\nmatches the velocity sub-axes of the parent ``dimensions`` —\nenforced on the parent :class:`PhaseSpace` once the spatial\ndimension count is known at the root level.",
                  ),
                z.null(),
              ])
              .default(null),
          })
          .strict()
          .describe(
            "``[phase_space]`` — kinetic phase-space dimensions for >3D codes.\n\nGyrokinetic codes (GENE, GS2, GX, Gkeyll-GK) run on 5-D grids\n(3 spatial + 2 velocity); continuum-Vlasov codes use 6-D phase\nspace (3 spatial + 3 velocity). This block describes the\n*augmented* phase-space dimensionality without lifting the\n``Grid.dimensions`` cap on the spatial side.\n\nRequired when the simulation operates on a phase-space grid larger\nthan ``[grid].dimensions``. Optional otherwise. The root validator\nenforces consistency: ``[phase_space].dimensions[:n_spatial]``\nmust match ``[grid].dimensions`` when both are present.\n\n``storage`` is the sparse-block sub-table for continuum-Vlasov\ncodes.  Gyrokinetic runs omit it.",
          ),
        z.null(),
      ])
      .default(null),
    physics: z
      .union([
        z
          .object({
            hybrid: z
              .union([
                z
                  .object({
                    solver: z
                      .union([
                        z
                          .object({
                            current_smoothing: z
                              .union([z.number().int().gte(0), z.null()])
                              .default(null),
                            field_pusher: z.union([z.string(), z.null()]).default(null),
                            hyper_resistivity: z.union([z.number().gte(0), z.null()]).default(null),
                            preconditioner: z.union([z.string(), z.null()]).default(null),
                            resistivity: z.union([z.number().gte(0), z.null()]).default(null),
                            scheme: z.string(),
                          })
                          .catchall(z.union([z.any(), z.any()]))
                          .superRefine((value, ctx) => {
                            for (const key in value) {
                              let evaluated = [
                                "current_smoothing",
                                "field_pusher",
                                "hyper_resistivity",
                                "preconditioner",
                                "resistivity",
                                "scheme",
                              ].includes(key);
                              if (key.match(new RegExp("^x[-_]"))) {
                                evaluated = true;
                                const result = z.any().safeParse(value[key]);
                                if (!result.success) {
                                  ctx.addIssue({
                                    path: [key],
                                    code: "custom",
                                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                    params: {
                                      issues: result.error.issues,
                                    },
                                  });
                                }
                              }
                              if (!evaluated) {
                                const result = z.any().safeParse(value[key]);
                                if (!result.success) {
                                  ctx.addIssue({
                                    path: [key],
                                    code: "custom",
                                    message: `Invalid input: must match catchall schema`,
                                    params: {
                                      issues: result.error.issues,
                                    },
                                  });
                                }
                              }
                            }
                          })
                          .describe("``[physics.hybrid.solver]``. Extra keys accepted."),
                        z.null(),
                      ])
                      .default(null),
                  })
                  .catchall(z.union([z.any(), z.any()]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = ["solver"].includes(key);
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  })
                  .describe(
                    "``[physics.hybrid]`` — hybrid physics-model knobs. Extra keys accepted.",
                  ),
                z.null(),
              ])
              .default(null),
            mhd: z
              .union([
                z
                  .object({
                    gamma_eos: z.union([z.number().gt(0), z.null()]).default(null),
                    hall_term: z.union([z.boolean(), z.null()]).default(null),
                    resistivity: z.union([z.number().gte(0), z.null()]).default(null),
                    solver: z
                      .union([
                        z
                          .object({
                            divergence_cleaning: z.union([z.string(), z.null()]).default(null),
                            limiter: z.union([z.string(), z.null()]).default(null),
                            preconditioner: z.union([z.string(), z.null()]).default(null),
                            reconstruction: z.union([z.string(), z.null()]).default(null),
                            riemann: z.union([z.string(), z.null()]).default(null),
                            scheme: z.string(),
                          })
                          .catchall(z.union([z.any(), z.any()]))
                          .superRefine((value, ctx) => {
                            for (const key in value) {
                              let evaluated = [
                                "divergence_cleaning",
                                "limiter",
                                "preconditioner",
                                "reconstruction",
                                "riemann",
                                "scheme",
                              ].includes(key);
                              if (key.match(new RegExp("^x[-_]"))) {
                                evaluated = true;
                                const result = z.any().safeParse(value[key]);
                                if (!result.success) {
                                  ctx.addIssue({
                                    path: [key],
                                    code: "custom",
                                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                    params: {
                                      issues: result.error.issues,
                                    },
                                  });
                                }
                              }
                              if (!evaluated) {
                                const result = z.any().safeParse(value[key]);
                                if (!result.success) {
                                  ctx.addIssue({
                                    path: [key],
                                    code: "custom",
                                    message: `Invalid input: must match catchall schema`,
                                    params: {
                                      issues: result.error.issues,
                                    },
                                  });
                                }
                              }
                            }
                          })
                          .describe("``[physics.mhd.solver]``. Extra keys accepted."),
                        z.null(),
                      ])
                      .default(null),
                  })
                  .catchall(z.union([z.any(), z.any()]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = ["gamma_eos", "hall_term", "resistivity", "solver"].includes(
                        key,
                      );
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  })
                  .describe("``[physics.mhd]`` — MHD physics-model knobs. Extra keys accepted."),
                z.null(),
              ])
              .default(null),
            pic: z
              .union([
                z
                  .object({
                    omega_p_over_omega_c: z.union([z.number().gt(0), z.null()]).default(null),
                    solver: z
                      .union([
                        z
                          .object({
                            charge_correction: z.union([z.string(), z.null()]).default(null),
                            charge_smoothing: z
                              .union([z.number().int().gte(0), z.null()])
                              .default(null),
                            current_deposition: z.union([z.string(), z.null()]).default(null),
                            current_smoothing: z
                              .union([z.number().int().gte(0), z.null()])
                              .default(null),
                            field_solver: z.union([z.string(), z.null()]).default(null),
                            implicitness: z.union([z.number(), z.null()]).default(null),
                            preconditioner: z.union([z.string(), z.null()]).default(null),
                            pusher: z.union([z.string(), z.null()]).default(null),
                            scheme: z.string(),
                          })
                          .catchall(z.union([z.any(), z.any()]))
                          .superRefine((value, ctx) => {
                            for (const key in value) {
                              let evaluated = [
                                "charge_correction",
                                "charge_smoothing",
                                "current_deposition",
                                "current_smoothing",
                                "field_solver",
                                "implicitness",
                                "preconditioner",
                                "pusher",
                                "scheme",
                              ].includes(key);
                              if (key.match(new RegExp("^x[-_]"))) {
                                evaluated = true;
                                const result = z.any().safeParse(value[key]);
                                if (!result.success) {
                                  ctx.addIssue({
                                    path: [key],
                                    code: "custom",
                                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                                    params: {
                                      issues: result.error.issues,
                                    },
                                  });
                                }
                              }
                              if (!evaluated) {
                                const result = z.any().safeParse(value[key]);
                                if (!result.success) {
                                  ctx.addIssue({
                                    path: [key],
                                    code: "custom",
                                    message: `Invalid input: must match catchall schema`,
                                    params: {
                                      issues: result.error.issues,
                                    },
                                  });
                                }
                              }
                            }
                          })
                          .describe(
                            "``[physics.pic.solver]``. Extra keys accepted — vocabulary evolves.\n\n``current_smoothing`` / ``charge_smoothing`` count the binomial /\ncompensator filter passes per step (standard in WarpX, Smilei,\nPIConGPU, OSIRIS — already exposed on ``HybridSolver``).\n``charge_correction``, ``current_deposition`` adopt the openPMD\nED-PIC vocabulary; see :class:`ChargeCorrection`,\n:class:`CurrentDeposition`.",
                          ),
                        z.null(),
                      ])
                      .default(null),
                  })
                  .catchall(z.union([z.any(), z.any()]))
                  .superRefine((value, ctx) => {
                    for (const key in value) {
                      let evaluated = ["omega_p_over_omega_c", "solver"].includes(key);
                      if (key.match(new RegExp("^x[-_]"))) {
                        evaluated = true;
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: Key matching regex /${key}/ must match schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                      if (!evaluated) {
                        const result = z.any().safeParse(value[key]);
                        if (!result.success) {
                          ctx.addIssue({
                            path: [key],
                            code: "custom",
                            message: `Invalid input: must match catchall schema`,
                            params: {
                              issues: result.error.issues,
                            },
                          });
                        }
                      }
                    }
                  })
                  .describe("``[physics.pic]`` — PIC physics-model knobs. Extra keys accepted."),
                z.null(),
              ])
              .default(null),
            relativistic: z.boolean().default(false),
          })
          .catchall(z.union([z.any(), z.any()]))
          .superRefine((value, ctx) => {
            for (const key in value) {
              let evaluated = ["hybrid", "mhd", "pic", "relativistic"].includes(key);
              if (key.match(new RegExp("^x[-_]"))) {
                evaluated = true;
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: Key matching regex /${key}/ must match schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
              if (!evaluated) {
                const result = z.any().safeParse(value[key]);
                if (!result.success) {
                  ctx.addIssue({
                    path: [key],
                    code: "custom",
                    message: `Invalid input: must match catchall schema`,
                    params: {
                      issues: result.error.issues,
                    },
                  });
                }
              }
            }
          })
          .describe(
            "``[physics]`` — flags whose semantics are identical across models.\n\nExtra top-level keys under ``[physics]`` are accepted to leave room\nfor v1.1+ additions (``[physics.vlasov]`` in particular).",
          ),
        z.null(),
      ])
      .default(null),
    probes: z
      .array(
        z
          .object({
            fields: z.union([z.array(z.string()), z.null()]).default(null),
            frame: z.union([z.string(), z.null()]).default(null),
            name: z.string(),
            position: z.union([z.any(), z.null()]).default(null),
            trajectory: z.union([z.string(), z.null()]).default(null),
          })
          .strict()
          .describe(
            'One entry in ``[[probes]]`` — fixed or trajectory sampler.\n\n``fields`` controls which dataset fields the probe samples. Two modes:\n\n- ``fields = None`` (omitted) — sample every **storage-primitive**\n  field present in the dataset at probe time. Storage primitives are\n  what readers expose via ``available_fields()`` — moments and EM\n  fields actually on disk, never derived quantities like ``|B|`` or\n  ``beta``. Users who want derived quantities listed must request\n  them explicitly. The narrow default keeps probe time-series cheap\n  on big runs.\n- ``fields = [...]`` — sample exactly this list. Names that don\'t\n  resolve at sample time should fail loudly (per CLAUDE.md "fail\n  loud on unmatched names" guidance); resolution against\n  ``available_fields()`` happens in the probe sampler, not here.',
          ),
      )
      .optional(),
    restart: z
      .union([
        z
          .object({
            from: z.union([z.string(), z.array(z.string())]),
            mode: z.union([z.enum(["hot", "cold"]), z.null()]).default(null),
            restore: z
              .union([z.array(z.enum(["fields", "particles", "auxiliary"])), z.null()])
              .default(null),
            step: z.union([z.number().int().gte(0), z.null()]).default(null),
            time: z.union([z.number().gte(0), z.null()]).default(null),
          })
          .strict()
          .describe(
            '``[restart]`` — continuation pointer from a prior run.\n\n``from`` is the path (or paths) to the restart artifact:\n\n* a single file (``./chk_000030.h5``),\n* a directory of per-rank checkpoints (``./restart_30000/``),\n* a glob pattern, or\n* an explicit list of per-rank files for runs whose names don\'t\n  follow the source code\'s convention (relocated reruns, mixed\n  naming schemes).\n\nWhether the path resolves to one file or many is determined at\nread time by the filesystem and the code, not by the schema.\n\n``restore`` enables partial restart — restarting only the listed\nstate categories rather than all of them (e.g., fields-only\ncontinuation that re-initializes particles from a fresh\ndistribution). ``mode`` distinguishes a full state reload\n(``"hot"``) from a setup-restart that re-applies initial\nconditions on top of the saved geometry (``"cold"``). Both\noptional; a missing ``restore`` means the full state is restored.',
          ),
        z.null(),
      ])
      .default(null),
    run: z
      .object({
        authors: z.array(z.any()).optional(),
        date: z.union([z.string().date(), z.null()]).default(null),
        description: z.union([z.string(), z.null()]).default(null),
        doi: z.union([z.string(), z.null()]).default(null),
        embargo: z.union([z.string().date(), z.null()]).default(null),
        ensemble: z
          .union([
            z
              .object({ member_id: z.number().int().gt(0), total: z.number().int().gt(0) })
              .strict()
              .describe(
                "``[run.ensemble]`` — ensemble-member identity for stochastic runs.\n\nRequired for cosmological PIC, turbulence realizations, and any other\nsetup where multiple runs share initial conditions modulo a random\nseed. ``member_id`` is 1-indexed and bounded by ``total``; the\nvalidator enforces ``1 <= member_id <= total``.",
              ),
            z.null(),
          ])
          .default(null),
        funding: z.array(z.string()).optional(),
        git_sha: z.union([z.string(), z.null()]).default(null),
        host: z.union([z.string(), z.null()]).default(null),
        license: z.union([z.string(), z.null()]).default(null),
        name: z.string(),
        random_seed: z.union([z.number().int(), z.null()]).default(null),
        resources: z
          .union([
            z
              .object({
                allocations: z
                  .array(
                    z
                      .object({
                        count: z.number().int().gt(0),
                        hardware: z.string(),
                        hours: z.number().gte(0),
                        type: z.enum(["cpu", "gpu", "tpu", "accelerator"]),
                      })
                      .strict()
                      .describe(
                        "One entry in ``[[run.resources.allocations]]`` (heterogeneous HW).",
                      ),
                  )
                  .optional(),
                carbon_kg_co2eq: z.union([z.number().gte(0), z.null()]).default(null),
                cpu_core_hours: z.union([z.number().gte(0), z.null()]).default(null),
                cpu_type: z.union([z.string(), z.null()]).default(null),
                energy_kwh: z.union([z.number().gte(0), z.null()]).default(null),
                gpu_hours: z.union([z.number().gte(0), z.null()]).default(null),
                mpi_ranks: z.union([z.number().int().gt(0), z.null()]).default(null),
                mpi_topology: z.union([z.array(z.number().int().gt(0)), z.null()]).default(null),
                node_hours: z.union([z.number().gte(0), z.null()]).default(null),
                nodes: z.union([z.number().int().gt(0), z.null()]).default(null),
                peak_memory_gb: z.union([z.number().gte(0), z.null()]).default(null),
                wall_clock_hours: z.union([z.number().gte(0), z.null()]).default(null),
              })
              .strict()
              .describe("``[run.resources]`` — runtime accounting (all keys optional)."),
            z.null(),
          ])
          .default(null),
      })
      .strict()
      .describe("``[run]`` — identity + provenance of THIS run."),
    schema: z
      .object({
        created: z.union([z.string().date(), z.null()]).default(null),
        version: z.string(),
      })
      .strict()
      .describe("``[schema]`` — schema version + creation date."),
    species: z
      .array(
        z
          .object({
            charge: z.union([z.number(), z.null()]).default(null),
            charge_to_mass: z.union([z.number(), z.null()]).default(null),
            closure: z.union([z.string(), z.null()]).default(null),
            density: z.union([z.number().gte(0), z.null()]).default(null),
            drift_velocity: z.union([z.any(), z.null()]).default(null),
            gamma_eos: z.union([z.number().gt(0), z.null()]).default(null),
            gamma_eos_par: z.union([z.number().gt(0), z.null()]).default(null),
            gamma_eos_perp: z.union([z.number().gt(0), z.null()]).default(null),
            inertia: z.union([z.number().gte(0), z.null()]).default(null),
            mass: z.union([z.number().gt(0), z.null()]).default(null),
            name: z.string(),
            particles_per_cell: z
              .union([
                z.number().int().gte(0),
                z.array(z.number().int().gte(0)).min(3).max(3),
                z.null(),
              ])
              .default(null),
            shape: z.union([z.string(), z.null()]).default(null),
            temperature: z.union([z.number().gte(0), z.null()]).default(null),
            thermal_velocity: z.union([z.any(), z.null()]).default(null),
            tracer: z.boolean().default(false),
          })
          .strict()
          .describe(
            "One entry in ``[[species]]``.\n\nProvide either ``(charge, mass)`` OR ``charge_to_mass``, not both.\nValidated after the fact.\n\nSpecies are indexed in declaration order — ``_s0`` binds to the\nfirst ``[[species]]`` entry, ``_s1`` to the second, etc. Reordering\nentries is a breaking change to any downstream field-name reference\nthat uses the ``_sN`` suffix.",
          ),
      )
      .min(1),
    time: z
      .object({
        cfl: z.union([z.number(), z.null()]).default(null),
        dt: z.union([z.number().gte(0), z.null()]).default(null),
        dt_field: z.union([z.number(), z.null()]).default(null),
        dt_max: z.union([z.number(), z.null()]).default(null),
        dt_min: z.union([z.number(), z.null()]).default(null),
        field_substeps: z.union([z.number().int().gt(0), z.null()]).default(null),
        n_steps: z.number().int().gt(0),
        scheme: z.string().default("fixed"),
        splitting: z.union([z.string(), z.null()]).default(null),
        t_end: z.number(),
        t_start: z.number(),
      })
      .strict()
      .describe(
        "``[time]`` — temporal integration controls.\n\nScheme-specific keys are deliberately *not* modelled as a discriminated\nunion — the vocabulary is still settling and the cost of a wrong shape\nhere is low. v1.0 enforces only the cross-field invariants that are\nunambiguous:\n\n- fixed/subcycled require ``dt > 0`` (the integration step);\n- subcycled requires ``field_substeps`` (``dt_field`` is recommended\n  but advisory, not enforced);\n- adaptive omits ``dt`` (or accepts any non-negative value as a hint);\n  the runtime derives the first step from ``cfl`` / ``dt_min`` /\n  ``dt_max`` and owns CFL bookkeeping thereafter.\n\nA future v1.1 may formalise these as a discriminated union once codes\nconverge on a common spelling.",
      ),
    units: z.discriminatedUnion("system", [
      z
        .object({
          reference_charge: z.union([z.number(), z.null()]).default(null),
          reference_density: z.number().gt(0),
          reference_mass: z.union([z.number().gt(0), z.null()]).default(null),
          reference_species: z.string().default("electrons"),
          scaling_description: z.union([z.string(), z.null()]).default(null),
          scaling_factor: z.union([z.number(), z.null()]).default(null),
          speed_of_light: z.union([z.number().gt(0), z.null()]).default(null),
          system: z.literal("PIC"),
        })
        .strict()
        .describe('``[units]`` with ``system = "PIC"``.'),
      z
        .object({
          reference_b_field: z.number().gt(0),
          reference_density: z.number().gt(0),
          reference_length: z.number().gt(0),
          scaling_description: z.union([z.string(), z.null()]).default(null),
          scaling_factor: z.union([z.number(), z.null()]).default(null),
          system: z.literal("MHD"),
        })
        .strict()
        .describe('``[units]`` with ``system = "MHD"``.'),
      z
        .object({
          scaling_description: z.union([z.string(), z.null()]).default(null),
          scaling_factor: z.union([z.number(), z.null()]).default(null),
          system: z.literal("SI"),
        })
        .strict()
        .describe('``[units]`` with ``system = "SI"`` — already SI; no refs needed.'),
      z
        .object({
          reference: z
            .object({
              b_field: z.union([z.number().gt(0), z.null()]).default(null),
              charge: z.union([z.number(), z.null()]).default(null),
              density: z.union([z.number().gt(0), z.null()]).default(null),
              e_field: z.union([z.number().gt(0), z.null()]).default(null),
              length: z.number().gt(0),
              mass: z.union([z.number().gt(0), z.null()]).default(null),
              time: z.union([z.number().gt(0), z.null()]).default(null),
              velocity: z.union([z.number().gt(0), z.null()]).default(null),
            })
            .strict()
            .describe('``[units.reference]`` sub-table for ``system = "custom"``.'),
          scaling_description: z.union([z.string(), z.null()]).default(null),
          scaling_factor: z.union([z.number(), z.null()]).default(null),
          system: z.literal("custom"),
        })
        .strict()
        .describe('``[units]`` with ``system = "custom"``.'),
    ]),
  })
  .catchall(z.union([z.any(), z.any()]))
  .superRefine((value, ctx) => {
    for (const key in value) {
      let evaluated = [
        "bodies",
        "boundary_conditions",
        "collisions",
        "coordinates",
        "drivers",
        "grid",
        "initial_conditions",
        "model",
        "output",
        "phase_space",
        "physics",
        "probes",
        "restart",
        "run",
        "schema",
        "species",
        "time",
        "units",
      ].includes(key);
      if (key.match(new RegExp("^x[-_]"))) {
        evaluated = true;
        const result = z.any().safeParse(value[key]);
        if (!result.success) {
          ctx.addIssue({
            path: [key],
            code: "custom",
            message: `Invalid input: Key matching regex /${key}/ must match schema`,
            params: {
              issues: result.error.issues,
            },
          });
        }
      }
      if (!evaluated) {
        const result = z.any().safeParse(value[key]);
        if (!result.success) {
          ctx.addIssue({
            path: [key],
            code: "custom",
            message: `Invalid input: must match catchall schema`,
            params: {
              issues: result.error.issues,
            },
          });
        }
      }
    }
  })
  .describe(
    "Root model for a pypic simulation.toml v1.0 document.\n\nRequired top-level sections per v1.0:\n    [schema], [model], [run], [time], [grid], [units],\n    [coordinates], and at least one [[species]] entry.\n\nOptional sections may be omitted entirely.\n\nExtension policy at root: unknown keys must start with ``x-`` or\n``x_``. Known optional sections that are present are strictly\nvalidated.\n\n``[schema].version`` is the single discriminator for both the\nTOML config and the on-disk vocabulary it describes; v1.x is\nadditive-only per ``schema.md`` §1 *Versioning*.",
  );
export type SimulationConfig = z.infer<typeof SimulationSchema>;
